/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RenderLocalRouteImport } from './routes/render-local'
import { Route as IndexRouteImport } from './routes/index'

const RenderLocalRoute = RenderLocalRouteImport.update({
  id: '/render-local',
  path: '/render-local',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/render-local': typeof RenderLocalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/render-local': typeof RenderLocalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/render-local': typeof RenderLocalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/render-local'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/render-local'
  id: '__root__' | '/' | '/render-local'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RenderLocalRoute: typeof RenderLocalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/render-local': {
      id: '/render-local'
      path: '/render-local'
      fullPath: '/render-local'
      preLoaderRoute: typeof RenderLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RenderLocalRoute: RenderLocalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
